import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image
from rclpy.qos import QoSProfile, QoSReliabilityPolicy, QoSDurabilityPolicy
import numpy as np
import cv2
import serial

def get_safe_exposure_level(flat, clip_percent=0.05):
    # Returns the average brightness of the image, IGNORING the darkest and brightest clip_percent of pixels. generated by gemini

    # 1. Flatten image to 1D array for easy calculation
    #flat = image.flatten()

    # 2. Get the thresholds using Percentile
    # This automatically sorts the pixels and finds the value at 5% and 95%
    # This is mathematically equivalent to the histogram walk, but faster.
    low_thresh = np.percentile(flat, clip_percent * 100)
    high_thresh = np.percentile(flat, (1 - clip_percent) * 100)
    #print(low_thresh, high_thresh)

    # 3. Create a mask (Boolean array)
    # We only want pixels strictly between these two values
    mask = (flat >= low_thresh) & (flat <= high_thresh)

    # 4. Calculate Mean of VALID pixels only
    valid_pixels = flat[mask]

    # Safety check: if the image is solid black/white, valid_pixels might be empty
    if valid_pixels.size == 0:
        return np.mean(flat) # Fallback to standard mean

    return np.mean(valid_pixels)

class ImageSubscriber(Node):
    def __init__(self):
        super().__init__('auto_exp')
        self.subscription = self.create_subscription(Image, '/mono_left', self.callback, QoSProfile(depth=1, reliability=QoSReliabilityPolicy.BEST_EFFORT))
        self.cnt = 0
        self.shutter_spd_us = 10000
        self.ser = serial.Serial('/dev/ttyAMA2', 921600)
    def close(self):
        if self.ser and self.ser.is_open:
            self.ser.close()
    def __enter__(self):
        return self
    def __exit__(self, exc_type, exc_val, exc_tb):
        self.close()
    def __del__(self):
        self.close()
    def callback(self, msg):
        self.cnt = self.cnt + 1
        if self.cnt > 4:
            self.cnt = 0;
            flat_img = np.frombuffer(msg.data, dtype=np.uint8)
            avg_bright = get_safe_exposure_level(flat_img)
            #avg_bright = np.mean(img)
            if avg_bright <= 100 or avg_bright >= 120:
                adj = 1 + (110 / avg_bright - 1) * 0.1
                self.shutter_spd_us = int(self.shutter_spd_us * adj)
                if self.shutter_spd_us > 40000: # 20fps exposure time limit
                    self.shutter_spd_us = 40000
                elif self.shutter_spd_us < 1000:
                    self.shutter_spd_us = 1000
                #print(self.shutter_spd_us)
                buf = struct.pack('<H', self.shutter_spd_us)
                self.ser.write(self.shutter_spd_us.to_bytes(2, "little"))
                self.ser.flush()

def main(args=None):
    rclpy.init(args=args)
    node = ImageSubscriber()
    rclpy.spin(node)
    node.destroy_node()
    rclpy.shutdown()

if __name__ == '__main__':
    main()
